name: CLI Deploy
on:
  push:
    branches: ['main']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Quave Cloud CLI
        uses: zcloud-ws/zcloud-deploy-action@main
        with:
          env-token: ${{ secrets.QUAVE_CLOUD_ENV_TOKEN }}
          env: "joaovictornsv-blog-production"
